# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build-test:
    docker:
      - image: wordpress:php7.2-apache
        entrypoint: "docker-entrypoint.sh"
        command: "apache2-foreground"
      - image: circleci/mysql:5.7-ram
    steps:
      - checkout
      - run:
         name: Update and install dependencies
         command: |
            apt-get update
            apt-get install -y mysql-client
            apt-get install -y rsync
            apt-get install -y git
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      # Install WP CLI
      - run:
         name: Install wp-cli
         command: |
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            php wp-cli.phar --info
            chmod +x wp-cli.phar
            mv wp-cli.phar /usr/local/bin/wp
            wp --info
      # Install site plugins and themes
      - run:
        name: Install site plugins and themes
        command: |
          rsync -av ~/project/themes /var/www/html/wp-content
          rsync -av ~/project/plugins /var/www/html/wp-content
          rm -rf ~/project/themes
          rm -rf ~/project/plugins
      # Install WordPress
      - run: wp config create --path="/var/www/html" --dbname=circle_test --dbuser=root --dbpass="" --dbhost="127.0.0.1" --allow-root --skip-check
      - run: wp core install --path="/var/www/html" --url="localhost" --title="123" --admin_user=123 --admin_password=123 --admin_email=admin@example.com --allow-root
      - run: sed -i 's/192.168.33.10/localhost/g' ~/project/database/database-cp3402-2019-team25/mysql.sql
      - run: mysql -u'root' -h 127.0.0.1 circle_test < ~/project/database/database-cp3402-2019-team25/mysql.sql
      - run:
         name: is installed
         command: |
            wp core is-installed --path="/var/www/html" --allow-root
            echo $?
      - run: wp theme activate --path="/var/www/html" theme-cp3402-2019-team25 --allow-root
#      - run: wp plugin activate --path="/var/www/html" plugin-name --allow-root
      - run: service apache2 start
  staging:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d7:1c:7d:51:cc:ec:09:2d:91:29:f9:80:5c:27:fc:46"
      - checkout
      - run: ping -c 4 staging.cp3402-2019-team25.dns-cloud.net
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: scp -r database CircleCI@staging.cp3402-2019-team25.dns-cloud.net:database
      - run: scp -r themes CircleCI@staging.cp3402-2019-team25.dns-cloud.net:themes
      - run: scp -r plugins CircleCI@staging.cp3402-2019-team25.dns-cloud.net:plugins
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo apt-get update; sudo apt-get install -y apache2 mysql-server mysql-client php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mysql php-mbstring php-xml libapache2-mod-php rsync git"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo service apache2 stop"
      # Create WpAdmin user and wordpress database in mysql
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo mysql -u'root' -e 'CREATE DATABASE IF NOT EXISTS wordpress'"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo sed -i 's/scotchbox/wordpress/g' ~/database/database-cp3402-2019-team25/create_user.sql"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo mysql -u'root' < ~/database/database-cp3402-2019-team25/create_user.sql"
      # Install WP CLI
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo php wp-cli.phar --info"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo chmod +x wp-cli.phar"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo mv wp-cli.phar /usr/local/bin/wp"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp --info"
      # Install site plugins and themes
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo rsync -av ~/database /var/www/html/wp-content"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo rsync -av ~/themes /var/www/html/wp-content"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo rsync -av ~/plugins /var/www/html/wp-content"
      # Install WordPress
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp core download --path='/var/www/html' --force --allow-root"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp config create --path='/var/www/html' --force --dbname=wordpress --dbuser=WebAdmin --dbpass='gG5XCvUSL4keOwamsEz' --dbhost='127.0.0.1'" --allow-root
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp core install --path='/var/www/html' --url='https:\/\/staging.cp3402-2019-team25.dns-cloud.net' --title='a2-cp3402-2019-team25' --admin_user=WpAdmin --admin_password=gG5XCvUSL4keOwamsEz --admin_email=admin@example.com" --allow-root
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo sed -i 's/192.168.33.10/staging.cp3402-2019-team25.dns-cloud.net/g' ~/database/database-cp3402-2019-team25/mysql.sql"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo mysql -u'WebAdmin' -p'gG5XCvUSL4keOwamsEz' -h 127.0.0.1 wordpress < ~/database/database-cp3402-2019-team25/mysql.sql"
      - run:
         name: is isntalled
         command: |
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp core is-installed --path='/var/www/html' --allow-root"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "echo $?"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp theme activate --path='/var/www/html' theme-cp3402-2019-team25 --allow-root"
#      - run: wp plugin activate --path="/var/www/html" plugin-name --allow-root
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo rm -rf ~/database"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo rm -rf ~/themes"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo rm -rf ~/plugins"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo rm -f ~/wp-cli.phar"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo service apache2 start"
      - run: git config --global user.email "3954937+Xett@users.noreply.github.com"
      - run: git config --global user.name "Xett"
      - run: git add --all
      - run: git commit -m "Update submodule commit references" || true
      - run: git push || true
  deployment:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "68:10:2e:d0:ec:4b:2c:44:17:cd:97:50:18:d0:70:39"
      - checkout
      - run: ping -c 4 deployment.cp3402-2019-team25.dns-cloud.net
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: scp -r database CircleCI@deployment.cp3402-2019-team25.dns-cloud.net:database
      - run: scp -r themes CircleCI@deployment.cp3402-2019-team25.dns-cloud.net:themes
      - run: scp -r plugins CircleCI@deployment.cp3402-2019-team25.dns-cloud.net:plugins
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo apt-get update; sudo apt-get install -y apache2 mysql-server mysql-client php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mysql php-mbstring php-xml libapache2-mod-php rsync git"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo service apache2 stop"
      # Create WpAdmin user and wordpress database in mysql
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo mysql -u'root' -e 'CREATE DATABASE IF NOT EXISTS wordpress'"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo sed -i 's/scotchbox/wordpress/g' ~/database/database-cp3402-2019-team25/create_user.sql"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo mysql -u'root' < ~/database/database-cp3402-2019-team25/create_user.sql"
      # Install WP CLI
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo php wp-cli.phar --info"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo chmod +x wp-cli.phar"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo mv wp-cli.phar /usr/local/bin/wp"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp --info"
      # Install site plugins and themes
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo rsync -av ~/database /var/www/html/wp-content"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo rsync -av ~/themes /var/www/html/wp-content"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo rsync -av ~/plugins /var/www/html/wp-content"
      # Install WordPress
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp core download --path='/var/www/html' --force --allow-root"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp config create --path='/var/www/html' --force --dbname=wordpress --dbuser=WebAdmin --dbpass='gG5XCvUSL4keOwamsEz' --dbhost='127.0.0.1'" --allow-root
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp core install --path='/var/www/html' --url='https:\/\/deployment.cp3402-2019-team25.dns-cloud.net' --title='a2-cp3402-2019-team25' --admin_user=WpAdmin --admin_password=gG5XCvUSL4keOwamsEz --admin_email=admin@example.com" --allow-root
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo sed -i 's/192.168.33.10/staging.cp3402-2019-team25.dns-cloud.net/g' ~/database/database-cp3402-2019-team25/mysql.sql"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo mysql -u'WebAdmin' -p'gG5XCvUSL4keOwamsEz' -h 127.0.0.1 wordpress < ~/database/database-cp3402-2019-team25/mysql.sql"
      - run:
         name: is isntalled
         command: |
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp core is-installed --path='/var/www/html' --allow-root"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "echo $?"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp theme activate --path='/var/www/html' theme-cp3402-2019-team25 --allow-root"
#      - run: wp plugin activate --path="/var/www/html" plugin-name --allow-root
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo rm -rf ~/database"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo rm -rf ~/themes"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo rm -rf ~/plugins"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo rm -f ~/wp-cli.phar"
      - run: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo service apache2 start"
workflows:
  version: 2
  staging:
    jobs:
      - build-test
      - staging:
          requires:
              - build-test
  hourly-staging:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-test
      - staging:
          requires:
              - build-test
  deployment:
    jobs:
      - deployment:
          type: approval
