# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: wordpress:php7.2-apache
        entrypoint: "docker-entrypoint.sh"
        command: "apache2-foreground"
      - image: circleci/mysql:5.7-ram

    steps:
      - checkout

      - run:
         name: update and install dependencies
         command: |
            apt-get update
            apt-get install -y mysql-client
            apt-get install -y rsync
            apt-get install -y git
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      # Install WP CLI
      - run: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      - run: php wp-cli.phar --info
      - run: chmod +x wp-cli.phar
      - run: mv wp-cli.phar /usr/local/bin/wp
      - run: wp --info

      # Install site plugins and themes
      - run: rsync -av ~/project/themes /var/www/html/wp-content
      - run: rsync -av ~/project/plugins /var/www/html/wp-content
      - run: rm -rf ~/project/themes
      - run: rm -rf ~/project/plugins

      # Install WordPress
      - run: wp config create --path="/var/www/html" --dbname=circle_test --dbuser=root --dbpass="" --dbhost="127.0.0.1" --allow-root --skip-check
      - run: wp core install --path="/var/www/html" --url="localhost" --title="123" --admin_user=123 --admin_password=123 --admin_email=admin@example.com --allow-root
      - run: sed -i 's/192.168.33.10/localhost/g' ~/project/database/Wordpress-Database-Template/mysql.sql
      - run: mysql -u'root' -h 127.0.0.1 circle_test < ~/project/database/Wordpress-Database-Template/mysql.sql
      - run:
         name: is isntalled
         command: |
            wp core is-installed --path="/var/www/html" --allow-root
            echo $?
      - run: wp theme activate --path="/var/www/html" Wordpress-Theme-Template --allow-root
      - run: wp plugin activate --path="/var/www/html" Wordpress-Plugin-Template --allow-root



      # run tests with phpunit or codecept
      - run: curl 127.0.0.1

      - run: service apache2 start
