# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build-test:
    docker:
      - image: wordpress:php7.2-apache
        entrypoint: "docker-entrypoint.sh"
        command: "apache2-foreground"
      - image: circleci/mysql:5.7-ram
    steps:
      - checkout
      - run:
         name: update and install dependencies
         command: |
            apt-get update
            apt-get install -y mysql-client
            apt-get install -y rsync
            apt-get install -y git
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      # Install WP CLI
      - run: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      - run: php wp-cli.phar --info
      - run: chmod +x wp-cli.phar
      - run: mv wp-cli.phar /usr/local/bin/wp
      - run: wp --info
      # Install site plugins and themes
      - run: rsync -av ~/project/themes /var/www/html/wp-content
      - run: rsync -av ~/project/plugins /var/www/html/wp-content
      - run: rm -rf ~/project/themes
      - run: rm -rf ~/project/plugins
      # Install WordPress
      - run: wp config create --path="/var/www/html" --dbname=circle_test --dbuser=root --dbpass="" --dbhost="127.0.0.1" --allow-root --skip-check
      - run: wp core install --path="/var/www/html" --url="localhost" --title="123" --admin_user=123 --admin_password=123 --admin_email=admin@example.com --allow-root
      - run: sed -i 's/192.168.33.10/localhost/g' ~/project/database/database-cp3402-2019-team25/mysql.sql
      - run: mysql -u'root' -h 127.0.0.1 circle_test < ~/project/database/database-cp3402-2019-team25/mysql.sql
      - run:
         name: is installed
         command: |
            wp core is-installed --path="/var/www/html" --allow-root
            echo $?
      - run: wp theme activate --path="/var/www/html" theme-cp3402-2019-team25 --allow-root
#      - run: wp plugin activate --path="/var/www/html" plugin-name --allow-root
      - run: service apache2 start
  staging:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d7:1c:7d:51:cc:ec:09:2d:91:29:f9:80:5c:27:fc:46"
      - checkout
      - run: ping -c 4 staging.cp3402-2019-team25.dns-cloud.net
      - run: ls -la
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo apt-get update; sudo apt-get install -y apache2 mysql-server mysql-client php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mysql php-mbstring php-xml libapache2-mod-php rsync git"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo service apache2 stop"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo git clone https://github.com/cp3402-students/a2-cp3402-2019-team25.git"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo git submodule init; sudo git submodule update --remote"
      # Create WpAdmin user and wordpress database in mysql
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo mysql -u'root' -e 'CREATE DATABASE IF NOT EXISTS wordpress'"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sed -i 's/scotchbox/wordpress/g' ~/project/database/database-cp3402-2019-team25/create_user.sql"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo mysql -u'root' < ~/project/database/database-cp3402-2019-team25/create_user.sql"
      # Install WP CLI
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "php wp-cli.phar --info"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "chmod +x wp-cli.phar"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "mv wp-cli.phar /usr/local/bin/wp"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "wp --info"
      # Install site plugins and themes
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "rsync -av ~/project/themes /var/www/html/wp-content"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "rsync -av ~/project/plugins /var/www/html/wp-content"
      # Install WordPress
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "wp config create --path='/var/www/html' --dbname=wordpress --dbuser=WebAdmin --dbpass='gG5XCvUSL4keOwamsEz' --dbhost='127.0.0.1'"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "wp core install --path='/var/www/html' --url='https:\/\/staging.cp3402-2019-team25.dns-cloud.net' --admin_user=WpAdmin --admin_password=gG5XCvUSL4keOwamsEz --admin_email=admin@example.com"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sed -i 's/192.168.33.10/https:\/\/staging.cp3402-2019-team25.dns-cloud.net/g' ~/a2-cp3402-2019-team25/database/database-cp3402-2019-team25/mysql.sql"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "mysql -u'WebAdmin' -p'gG5XCvUSL4keOwamsEz' -h 127.0.0.1 wordpress < ~/a2-cp3402-2019-team25/database/database-cp3402-2019-team25/mysql.sql"
      - run:
         name: is isntalled
         command: |
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "wp core is-installed --path='/var/www/html' --allow-root"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "echo $?"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "wp theme activate --path='/var/www/html' theme-cp3402-2019-team25 --allow-root"
#      - run: wp plugin activate --path="/var/www/html" plugin-name --allow-root
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "rm -rf ~/a2-cp3402-2019-team25"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "rm -rf ~/project"
      - run: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo service apache2 start"
  deployment:
    machine:
      enabled: true
    steps:
      - checkout
      - run: ping -c 4 deployment.cp3402-2019-team25.dns-cloud.net
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-test
      - staging:
          requires:
              - build-test
      - deployment:
          type: approval
          requires:
              - staging
