# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build-test:
    docker:
      - image: wordpress:php7.2-apache
        entrypoint: "docker-entrypoint.sh"
        command: "apache2-foreground"
      - image: circleci/mysql:5.7-ram
    steps:
      - checkout
      - run:
         name: Update and install dependencies
         command: |
            apt-get update
            apt-get install -y mysql-client
            apt-get install -y rsync
            apt-get install -y git
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
         name: Install wp-cli
         command: |
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            php wp-cli.phar --info
            chmod +x wp-cli.phar
            mv wp-cli.phar /usr/local/bin/wp
            wp --info
      - run:
          name: Install WordPress
          command: |
            wp config create --path="/var/www/html" --dbname=circle_test --dbuser=root --dbpass="" --dbhost="127.0.0.1" --allow-root --skip-check
            wp core install --path="/var/www/html" --url="localhost" --title="123" --admin_user=123 --admin_password=123 --admin_email=admin@example.com --allow-root
            wp core is-installed --path="/var/www/html" --allow-root
            echo $?
      - run:
          name: Install site plugins and themes
          command: |
            rsync -av ~/project/themes /var/www/html/wp-content
            rsync -av ~/project/plugins /var/www/html/wp-content
            wp theme activate --path="/var/www/html" theme-cp3402-2019-team25 --allow-root
            sed -i 's/192.168.33.10/localhost/g' ~/project/database/database-cp3402-2019-team25/mysql.sql
            mysql -u'root' -h 127.0.0.1 circle_test < ~/project/database/database-cp3402-2019-team25/mysql.sql
            rm -rf ~/project/themes
            rm -rf ~/project/plugins
      - run:
          name: Start apache2 webserver
          command: service apache2 start
  staging:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d7:1c:7d:51:cc:ec:09:2d:91:29:f9:80:5c:27:fc:46"
      - checkout
      - run:
          name: Ping server to see it is alive
          command: ping -c 4 staging.cp3402-2019-team25.dns-cloud.net
      - run:
          name: Stop apache2 webserver
          command: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo service apache2 stop"
      - run:
          name: Pull Submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Update and install dependencies
          command: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo apt-get update; sudo apt-get install -y apache2 mysql-server mysql-client php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mysql php-mbstring php-xml libapache2-mod-php rsync git"
      - run:
          name: Install WP CLI
          command: |
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo php wp-cli.phar --info"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo chmod +x wp-cli.phar"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo mv wp-cli.phar /usr/local/bin/wp"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp --info"
      - run:
          name: Download and install WordPress
          command: |
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp core download --path='/var/www/html' --force --allow-root"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp config create --path='/var/www/html' --force --dbname=wordpress --dbuser=WebAdmin --dbpass='gG5XCvUSL4keOwamsEz' --dbhost='127.0.0.1'" --allow-root
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp core install --path='/var/www/html' --url='https:\/\/staging.cp3402-2019-team25.dns-cloud.net' --title='a2-cp3402-2019-team25' --admin_user=WpAdmin --admin_password=gG5XCvUSL4keOwamsEz --admin_email=admin@example.com" --allow-root
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo sed -i 's/192.168.33.10/staging.cp3402-2019-team25.dns-cloud.net/g' ~/database/database-cp3402-2019-team25/mysql.sql"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo mysql -u'WebAdmin' -p'gG5XCvUSL4keOwamsEz' -h 127.0.0.1 wordpress < ~/database/database-cp3402-2019-team25/mysql.sql"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp core is-installed --path='/var/www/html' --allow-root"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "echo $?"
      - run:
          name: Copy database, themes and plugins
          command: |
            scp -r database CircleCI@staging.cp3402-2019-team25.dns-cloud.net:database
            scp -r themes CircleCI@staging.cp3402-2019-team25.dns-cloud.net:themes
            rsync -avh -e ssh plugins CircleCI@staging.cp3402-2019-team25.dns-cloud.net:/var/www/html/wp-content/plugins
      - run:
          name: Install website database plugins and themes, and cleanup
          command: |
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo rsync -av ~/database /var/www/html/wp-content"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo rsync -av ~/themes /var/www/html/wp-content"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp theme activate --path='/var/www/html' theme-cp3402-2019-team25 --allow-root"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp plugin deactivate wp-scss --allow-root"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp plugin deactivate elementor-pro --allow-root"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp plugin deactivate wordpress-seo --allow-root"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo wp plugin deactivate w3-total-cache --allow-root"
      - run:
          name: Create WpAdmin user and wordpress database on the MYSQL server
          command: |
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo mysql -u'root' -e 'CREATE DATABASE IF NOT EXISTS wordpress'"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo sed -i 's/scotchbox/wordpress/g' ~/database/database-cp3402-2019-team25/create_user.sql"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo mysql -u'root' < ~/database/database-cp3402-2019-team25/create_user.sql"
      - run:
          name: Cleanup server
          command: |
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo rm -rf ~/database"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo rm -rf ~/themes"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo rm -rf ~/plugins"
            ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo rm -f ~/wp-cli.phar"
      - run:
          name: Start apache2 webserver
          command: ssh CircleCI@staging.cp3402-2019-team25.dns-cloud.net -t "sudo service apache2 start"
      - run:
          name: Update submodules and push to github repo
          command: |
            git config --global user.email "3954937+Xett@users.noreply.github.com"
            git config --global user.name "Xett"
            git add --all
            git commit -m "Update submodule commit references" || true
            git push || true
  deployment:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "68:10:2e:d0:ec:4b:2c:44:17:cd:97:50:18:d0:70:39"
      - checkout
      - run:
          name: Ping server to see it is alive
          command: ping -c 4 deployment.cp3402-2019-team25.dns-cloud.net
      - run:
          name: Stop apache2 webserver
          command: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo service apache2 stop"
      - run:
          name: Pull Submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Update and install dependencies
          command: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo apt-get update; sudo apt-get install -y apache2 mysql-server mysql-client php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mysql php-mbstring php-xml libapache2-mod-php rsync git"
      - run:
          name: Install WP CLI
          command: |
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo php wp-cli.phar --info"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo chmod +x wp-cli.phar"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo mv wp-cli.phar /usr/local/bin/wp"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp --info"
      - run:
          name: Copy database, themes and plugins
          command: |
            scp -r database CircleCI@deployment.cp3402-2019-team25.dns-cloud.net:database
            scp -r themes CircleCI@deployment.cp3402-2019-team25.dns-cloud.net:themes
            rsync -avh -e ssh plugins CircleCI@staging.cp3402-2019-team25.dns-cloud.net:/var/www/html/wp-content/plugins
      - run:
          name: Install website database plugins and themes, and cleanup
          command: |
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo rsync -av ~/database /var/www/html/wp-content"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo rsync -av ~/themes /var/www/html/wp-content"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp theme activate --path='/var/www/html' theme-cp3402-2019-team25 --allow-root"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp plugin deactivate --path='/var/www/html' wp-scss --allow-root"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp plugin deactivate --path='/var/www/html' elementor-pro --allow-root"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp plugin deactivate --path='/var/www/html' wordpress-seo --allow-root"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp plugin deactivate --path='/var/www/html' w3-total-cache --allow-root"
      - run:
          name: Download and install WordPress
          command: |
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp core download --path='/var/www/html' --force --allow-root"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp config create --path='/var/www/html' --force --dbname=wordpress --dbuser=WebAdmin --dbpass='gG5XCvUSL4keOwamsEz' --dbhost='127.0.0.1'" --allow-root
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp core install --path='/var/www/html' --url='https:\/\/database.cp3402-2019-team25.dns-cloud.net' --title='a2-cp3402-2019-team25' --admin_user=WpAdmin --admin_password=gG5XCvUSL4keOwamsEz --admin_email=admin@example.com" --allow-root
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo sed -i 's/192.168.33.10/deployment.cp3402-2019-team25.dns-cloud.net/g' ~/database/database-cp3402-2019-team25/mysql.sql"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo mysql -u'WebAdmin' -p'gG5XCvUSL4keOwamsEz' -h 127.0.0.1 wordpress < ~/database/database-cp3402-2019-team25/mysql.sql"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo wp core is-installed --path='/var/www/html' --allow-root"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "echo $?"
      - run:
          name: Create WpAdmin user and wordpress database on the MYSQL server
          command: |
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo mysql -u'root' -e 'CREATE DATABASE IF NOT EXISTS wordpress'"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo sed -i 's/scotchbox/wordpress/g' ~/database/database-cp3402-2019-team25/create_user.sql"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo mysql -u'root' < ~/database/database-cp3402-2019-team25/create_user.sql"
      - run:
          name: Cleanup server
          command: |
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo rm -rf ~/database"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo rm -rf ~/themes"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo rm -rf ~/plugins"
            ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo rm -f ~/wp-cli.phar"
      - run:
          name: Start apache2 webserver
          command: ssh CircleCI@deployment.cp3402-2019-team25.dns-cloud.net -t "sudo service apache2 start"
      - run:
          name: Update submodules and push to github repo
          command: |
            git config --global user.email "3954937+Xett@users.noreply.github.com"
            git config --global user.name "Xett"
            git add --all
            git commit -m "Update submodule commit references" || true
            git push || true
workflows:
  version: 2
  staging:
    jobs:
      - build-test
      - staging:
          requires:
              - build-test
  hourly-staging:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-test
      - staging:
          requires:
              - build-test
  deployment:
    jobs:
      - deployment:
          type: approval
  daily-deployment:
    triggers:
      - schedule:
          cron: "45 23 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - deployment:
          type: approval
