# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build-test:
    docker:
      - image: wordpress:php7.2-apache
        entrypoint: "docker-entrypoint.sh"
        command: "apache2-foreground"
      - image: circleci/mysql:5.7-ram
    steps:
      - checkout
      - run:
         name: Update and install dependencies
         command: |
            apt-get update
            apt-get install -y mysql-client
            apt-get install -y rsync
            apt-get install -y git
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
         name: Install wp-cli
         command: |
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            php wp-cli.phar --info
            chmod +x wp-cli.phar
            mv wp-cli.phar /usr/local/bin/wp
            wp --info
      - run:
          name: Install WordPress
          command: |
            wp config create --path="/var/www/html" --dbname=circle_test --dbuser=root --dbpass="" --dbhost="127.0.0.1" --allow-root --skip-check
            wp core install --path="/var/www/html" --url="localhost" --title="123" --admin_user=123 --admin_password=123 --admin_email=admin@example.com --allow-root
            wp core is-installed --path="/var/www/html" --allow-root
            echo $?
      - run:
          name: Install site plugins and themes
          command: |
            rsync -av ~/project/themes /var/www/html/wp-content
            rsync -av ~/project/plugins /var/www/html/wp-content
            wp theme activate --path="/var/www/html" theme-cp3402-2019-team25 --allow-root
            sed -i 's/192.168.33.10/localhost/g' ~/project/database/database-cp3402-2019-team25/mysql.sql
            mysql -u'root' -h 127.0.0.1 circle_test < ~/project/database/database-cp3402-2019-team25/mysql.sql
            rm -rf ~/project/themes
            rm -rf ~/project/plugins
      - run:
          name: Start apache2 webserver
          command: service apache2 start
  staging:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d7:1c:7d:51:cc:ec:09:2d:91:29:f9:80:5c:27:fc:46"
      - checkout
      - run:
          name: Ping server to see it is alive
          command: ping -c 4 35.201.21.232
      - run:
          name: Stop apache2 webserver
          command: ssh CircleCI@35.201.21.232 -t "sudo service apache2 stop"
      - run:
          name: Set permissions to be open
          command: ssh CircleCI@35.201.21.232 -t "sudo chmod -R 777 /var/www/html/wp-content"
      - run:
          name: Pull Submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Update and install dependencies
          command: ssh CircleCI@35.201.21.232 -t "sudo apt-get update; sudo apt-get install -y apache2 mysql-server mysql-client php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mysql php-mbstring php-xml libapache2-mod-php rsync git"
      - run:
          name: Install WP CLI
          command: |
            ssh CircleCI@35.201.21.232 -t "sudo curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
            ssh CircleCI@35.201.21.232 -t "sudo php wp-cli.phar --info"
            ssh CircleCI@35.201.21.232 -t "sudo chmod +x wp-cli.phar"
            ssh CircleCI@35.201.21.232 -t "sudo mv wp-cli.phar /usr/local/bin/wp"
            ssh CircleCI@35.201.21.232 -t "sudo wp --info"
      - run:
          name: Archive database, themes and plugins
          command: |
            tar czf database.tar.gz database
            tar czf themes.tar.gz themes
            tar czf plugins.tar.gz plugins
            tar czf uploads.tar.gz uploads
      - run:
          name: Copy database, themes and plugins
          command: |
            scp database.tar.gz CircleCI@35.201.21.232:~/
            scp themes.tar.gz CircleCI@35.201.21.232:~/
            scp plugins.tar.gz CircleCI@35.201.21.232:~/
            scp uploads.tar.gz CircleCI@35.201.21.232:~/
      - run:
          name: Clean themes and plugins
          command: |
            ssh CircleCI@35.201.21.232 -t "sudo rm -r /var/www/html/wp-content/themes"
            ssh CircleCI@35.201.21.232 -t "sudo rm -r /var/www/html/wp-content/plugins"
            ssh CircleCI@35.201.21.232 -t "sudo rm -r /var/www/html/wp-content/uploads"
      - run:
          name: Extract database, themes, plugins and uploads
          command: |
            ssh CircleCI@35.201.21.232 -t "sudo tar -C /var/www/html/wp-content -zxvf ~/themes.tar.gz"
            ssh CircleCI@35.201.21.232 -t "sudo tar -C /var/www/html/wp-content -zxvf ~/plugins.tar.gz"
            ssh CircleCI@35.201.21.232 -t "sudo tar -C /var/www/html/wp-content -zxvf ~/uploads.tar.gz"
            ssh CircleCI@35.201.21.232 -t "sudo tar -C ~/ -zxvf ~/database.tar.gz"
      - run:
          name: Install website database plugins and themes, and cleanup
          command: |
            ssh CircleCI@35.201.21.232 -t "sudo wp theme activate --path='/var/www/html' theme-cp3402-2019-team25 --allow-root"
      - run:
          name: Download and install WordPress
          command: |
            ssh CircleCI@35.201.21.232 -t "sudo wp core download --path='/var/www/html' --force --allow-root"
            ssh CircleCI@35.201.21.232 -t "sudo wp config create --path='/var/www/html' --force --dbname=wordpress --dbuser=WebAdmin --dbpass='gG5XCvUSL4keOwamsEz' --dbhost='127.0.0.1'" --allow-root
            ssh CircleCI@35.201.21.232 -t "sudo wp core install --path='/var/www/html' --url='http:\/\/35.201.21.232' --title='a2-cp3402-2019-team25' --admin_user=WpAdmin --admin_password=gG5XCvUSL4keOwamsEz --admin_email=admin@example.com" --allow-root
            ssh CircleCI@35.201.21.232 -t "sudo sed -i 's/192.168.33.10/35.201.21.232/g' ~/database/database-cp3402-2019-team25/mysql.sql"
            ssh CircleCI@35.201.21.232 -t "sudo mysql -u'WebAdmin' -p'gG5XCvUSL4keOwamsEz' -h 127.0.0.1 wordpress < ~/database/database-cp3402-2019-team25/mysql.sql"
            ssh CircleCI@35.201.21.232 -t "sudo wp core is-installed --path='/var/www/html' --allow-root"
            ssh CircleCI@35.201.21.232 -t "echo $?"
      - run:
          name: Create WpAdmin user and wordpress database on the MYSQL server
          command: |
            ssh CircleCI@35.201.21.232 -t "sudo mysql -u'root' -e 'CREATE DATABASE IF NOT EXISTS wordpress'"
            ssh CircleCI@35.201.21.232 -t "sudo sed -i 's/scotchbox/wordpress/g' ~/database/database-cp3402-2019-team25/create_user.sql"
            ssh CircleCI@35.201.21.232 -t "sudo mysql -u'root' < ~/database/database-cp3402-2019-team25/create_user.sql"
      - run:
          name: Cleanup server
          command: |
            ssh CircleCI@35.201.21.232 -t "sudo rm -rf ~/database"
            ssh CircleCI@35.201.21.232 -t "sudo rm -f ~/wp-cli.phar"
            rm database.tar.gz
            rm themes.tar.gz
            rm plugins.tar.gz
            rm uploads.tar.gz
      - run:
          name: Close permissions
          command: ssh CircleCI@35.201.21.232 -t "sudo chmod -R 755 /var/www/html/wp-content"
      - run:
          name: Start apache2 webserver
          command: ssh CircleCI@35.201.21.232 -t "sudo service apache2 start"
      - run:
          name: Update submodules and push to github repo
          command: |
            git config --global user.email "3954937+Xett@users.noreply.github.com"
            git config --global user.name "Xett"
            git add --all
            git commit -m "Update submodule commit references" || true
            git push || true
  deployment:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "68:10:2e:d0:ec:4b:2c:44:17:cd:97:50:18:d0:70:39"
      - checkout
      - run:
          name: Ping server to see it is alive
          command: ping -c 4 35.244.72.62
      - run:
          name: Stop apache2 webserver
          command: ssh CircleCI@35.244.72.62 -t "sudo service apache2 stop" || true
      - run:
          name: Set permissions to be open
          command: ssh CircleCI@35.244.72.62 -t "sudo chmod -R 777 /var/www/html/wp-content" || true
      - run:
          name: Pull Submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Update and install dependencies
          command: ssh CircleCI@35.244.72.62 -t "sudo apt-get update; sudo apt-get install -y apache2 mysql-server mysql-client php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mysql php-mbstring php-xml libapache2-mod-php rsync git"
      - run:
          name: Install WP CLI
          command: |
            ssh CircleCI@35.244.72.62 -t "sudo curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
            ssh CircleCI@35.244.72.62 -t "sudo php wp-cli.phar --info"
            ssh CircleCI@35.244.72.62 -t "sudo chmod +x wp-cli.phar"
            ssh CircleCI@35.244.72.62 -t "sudo mv wp-cli.phar /usr/local/bin/wp"
            ssh CircleCI@35.244.72.62 -t "sudo wp --info"
      - run:
          name: Archive database, themes and plugins
          command: |
            tar czf database.tar.gz database
            tar czf themes.tar.gz themes
            tar czf plugins.tar.gz plugins
            tar czf uploads.tar.gz uploads
      - run:
          name: Copy database, themes and plugins
          command: |
            scp database.tar.gz CircleCI@35.244.72.62:~/
            scp themes.tar.gz CircleCI@35.244.72.62:~/
            scp plugins.tar.gz CircleCI@35.244.72.62:~/
            scp uploads.tar.gz CircleCI@35.244.72.62:~/
      - run:
          name: Clean themes and plugins
          command: |
            ssh CircleCI@35.244.72.62 -t "sudo rm -r /var/www/html/wp-content/themes" || true
            ssh CircleCI@35.244.72.62 -t "sudo rm -r /var/www/html/wp-content/plugins" || true
            ssh CircleCI@35.244.72.62 -t "sudo rm -r /var/www/html/wp-content/uploads" || true
      - run:
          name: Extract database, themes, plugins and uploads
          command: |
            ssh CircleCI@35.244.72.62 -t "sudo tar -C /var/www/html/wp-content -zxvf ~/themes.tar.gz"
            ssh CircleCI@35.244.72.62 -t "sudo tar -C /var/www/html/wp-content -zxvf ~/plugins.tar.gz"
            ssh CircleCI@35.244.72.62 -t "sudo tar -C /var/www/html/wp-content -zxvf ~/uploads.tar.gz"
            ssh CircleCI@35.244.72.62 -t "sudo tar -C ~/ -zxvf ~/database.tar.gz"
      - run:
          name: Install website database plugins and themes, and cleanup
          command: |
            ssh CircleCI@35.244.72.62 -t "sudo wp theme activate --path='/var/www/html' theme-cp3402-2019-team25 --allow-root"
      - run:
          name: Download and install WordPress
          command: |
            ssh CircleCI@35.244.72.62 -t "sudo wp core download --path='/var/www/html' --force --allow-root"
            ssh CircleCI@35.244.72.62 -t "sudo wp config create --path='/var/www/html' --force --dbname=wordpress --dbuser=WebAdmin --dbpass='gG5XCvUSL4keOwamsEz' --dbhost='127.0.0.1'" --allow-root
            ssh CircleCI@35.244.72.62 -t "sudo wp core install --path='/var/www/html' --url='http:\/\/35.244.72.62' --title='a2-cp3402-2019-team25' --admin_user=WpAdmin --admin_password=gG5XCvUSL4keOwamsEz --admin_email=admin@example.com" --allow-root
            ssh CircleCI@35.244.72.62 -t "sudo sed -i 's/192.168.33.10/35.244.72.62/g' ~/database/database-cp3402-2019-team25/mysql.sql"
            ssh CircleCI@35.244.72.62 -t "sudo mysql -u'WebAdmin' -p'gG5XCvUSL4keOwamsEz' -h 127.0.0.1 wordpress < ~/database/database-cp3402-2019-team25/mysql.sql"
            ssh CircleCI@35.244.72.62 -t "sudo wp core is-installed --path='/var/www/html' --allow-root"
            ssh CircleCI@35.244.72.62 -t "echo $?"
      - run:
          name: Create WpAdmin user and wordpress database on the MYSQL server
          command: |
            ssh CircleCI@35.244.72.62 -t "sudo mysql -u'root' -e 'CREATE DATABASE IF NOT EXISTS wordpress'"
            ssh CircleCI@35.244.72.62 -t "sudo sed -i 's/scotchbox/wordpress/g' ~/database/database-cp3402-2019-team25/create_user.sql"
            ssh CircleCI@35.244.72.62 -t "sudo mysql -u'root' < ~/database/database-cp3402-2019-team25/create_user.sql"
      - run:
          name: Cleanup server
          command: |
            ssh CircleCI@35.244.72.62 -t "sudo rm -rf ~/database"
            ssh CircleCI@35.244.72.62 -t "sudo rm -f ~/wp-cli.phar"
            rm database.tar.gz
            rm themes.tar.gz
            rm plugins.tar.gz
            rm uploads.tar.gz
      - run:
          name: Close permissions
          command: ssh CircleCI@35.244.72.62 -t "sudo chmod -R 755 /var/www/html/wp-content"
      - run:
          name: Start apache2 webserver
          command: ssh CircleCI@35.244.72.62 -t "sudo service apache2 start"
      - run:
          name: Update submodules and push to github repo
          command: |
            git config --global user.email "3954937+Xett@users.noreply.github.com"
            git config --global user.name "Xett"
            git add --all
            git commit -m "Update submodule commit references" || true
            git push || true
workflows:
  version: 2
  staging:
    jobs:
      - build-test
      - staging:
          requires:
              - build-test
      - deployment:
          requires:
              - staging
  hourly-staging:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-test
      - staging:
          requires:
              - build-test
  deployment:
    jobs:
      - deployment:
          type: approval
  daily-deployment:
    triggers:
      - schedule:
          cron: "45 23 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - deployment:
          type: approval
